[project]
name = "advent-of-code"
version = "0.1.0"
description = "Advent of Code solutions"
requires-python = ">=3.13"
dependencies = [
    "toolz>=1.0.0"
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.4.2",
    "pytest-watcher>=0.4.3",
]

[tool.ruff]
lint.ignore = ["E741"]
